/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

export interface IListPlatformsHandler {
  (request?: IListPlatformsRequest): Promise<IListPlatformsResponse>;
}

export interface IListPlatformsRequest {
}
export interface IListPlatformsResponse {
  platforms: IListPlatformsResponsePlatforms[];
}

export interface IListPlatformsResponsePlatforms {
  name: string;
}
