/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadServiceHandler } from 'marvelous';

import { ListPlatformsCall } from '../../calls';
import { IListPlatformsHandler } from '../types';

export const listPlatformsHandler: IListPlatformsHandler = loadServiceHandler(ListPlatformsCall);
